=== giellalt/lang-kpv/src/abbr.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
   xmlns:xs="http://www.w3.org/2001/XMLSchema"
   xmlns:xml="http://www.w3.org/XML/1998/namespace">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
	     schemaLocation="xml.xsd"/>

<xs:element name="abbreviations">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="item" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="name" maxOccurs="4">
	      <xs:complexType>
		<xs:simpleContent>
		  <xs:extension base="xs:string">
		    <xs:attribute name="lang">
		      <xs:simpleType>
			<xs:restriction base="xs:string">
			  <xs:enumeration value="en"/>
			  <xs:enumeration value="fi"/>
			  <xs:enumeration value="kv"/>
			  <xs:enumeration value="ru"/>
			</xs:restriction>
		      </xs:simpleType>
		    </xs:attribute>
		    <xs:attribute name="abbr" type="xs:string"/>
		  </xs:extension>
		</xs:simpleContent>
	      </xs:complexType>
	    </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<!--

<xs:element name="field">
  <xs:complexType mixed="true">
    <xs:sequence>
    <xs:element ref="typical" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
     <xs:attribute name="field">
      <xs:simpleType>
	<xs:restriction base="xs:string">
	<xs:enumeration value="AERON"/>
	<xs:enumeration value="AGRIC"/>
	<xs:enumeration value="AMPH"/>
	<xs:enumeration value="ANAT"/>
	<xs:enumeration value="APPAREL"/>
	<xs:enumeration value="ARCH"/>
	<xs:enumeration value="ARCHEOL"/>
	<xs:enumeration value="ASTR"/>
	<xs:enumeration value="BIB"/>
	<xs:enumeration value="BIOL"/>
	<xs:enumeration value="BOT"/>
	<xs:enumeration value="CARDS"/>
	<xs:enumeration value="CARP"/>
	<xs:enumeration value="CELEBR"/>
	<xs:enumeration value="CHEM"/>
	<xs:enumeration value="CHRCH"/>
	<xs:enumeration value="ECON"/>
	<xs:enumeration value="ENT"/>
	<xs:enumeration value="ETHN"/>
	<xs:enumeration value="ETHNOG"/>
	<xs:enumeration value="FAUNA"/>
	<xs:enumeration value="FIN"/>
	<xs:enumeration value="FISH"/>
	<xs:enumeration value="FOLKL"/>
	<xs:enumeration value="FOREST"/>
	<xs:enumeration value="GAME"/>
	<xs:enumeration value="GASTR"/>
	<xs:enumeration value="GEOGR"/>
	<xs:enumeration value="GEOL"/>
	<xs:enumeration value="GRAM"/>
	<xs:enumeration value="HIST"/>
	<xs:enumeration value="HUNT"/>
	<xs:enumeration value="JUR"/>
	<xs:enumeration value="LAW"/>
	<xs:enumeration value="LING"/>
	<xs:enumeration value="LIT"/>
	<xs:enumeration value="MAM"/>
	<xs:enumeration value="MATH"/>
	<xs:enumeration value="MED"/>
	<xs:enumeration value="MIL"/>
	<xs:enumeration value="MIN"/>
	<xs:enumeration value="MUS"/>
	<xs:enumeration value="MYTH"/>
	<xs:enumeration value="ORN"/>
	<xs:enumeration value="PATHOL"/>
	<xs:enumeration value="PHARM"/>
	<xs:enumeration value="PHILOS"/>
	<xs:enumeration value="POLIT"/>
	<xs:enumeration value="PUNCT"/>
	<xs:enumeration value="RELIG"/>
	<xs:enumeration value="REPT"/>
	<xs:enumeration value="SILVA"/>
	<xs:enumeration value="SPORT"/>
	<xs:enumeration value="TECH"/>
	<xs:enumeration value="TEXT"/>
	<xs:enumeration value="THEATR"/>
	<xs:enumeration value="TIME"/>
	<xs:enumeration value="TOOL"/>
	<xs:enumeration value="TOPON"/>
	<xs:enumeration value="VEH"/>
	<xs:enumeration value="ZOOL"/>
	</xs:restriction>
       </xs:simpleType>
     </xs:attribute>
     <xs:attribute ref="cx"/>
    </xs:complexType>
</xs:element>

-->



</xs:schema>

=== giellalt/lang-kpv/src/kom-abbreviations.xml
<?xml version="1.0" encoding="UTF-8"?>
<abbreviations xsi:noNamespaceSchemaLocation="abbr.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <!-- УСЛОВНЫЕ СОКРАЩЕНИЯ ДЖЕНЬДӦДӦМЪЯС -->
   <!-- Abbreviatons used in the Komi-Russian Dictionary of 2000  -->
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="ав." lang="ru">авиация</name>
   </item>
   <item>
      <name abbr="anat." lang="en">anatomy</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="анат." lang="ru">анатомия</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="антроп." lang="ru">антропологический термин</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="апт." lang="ru">аптека</name>
   </item>
   <item>
      <name abbr="archeol." lang="en">archeology</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="археол." lang="ru">археология</name>
   </item>
   <item>
      <name abbr="arch." lang="en">architecture</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="архит." lang="ru">архитектура</name>
   </item>
   <item>
      <name abbr="astr." lang="en">astronomy</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="астр." lang="ru">астрономия</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">yskipersonainen</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="безл." lang="ru">безличное</name>
   </item>
   <item>
      <name abbr="biol." lang="en">biology</name>
      <name abbr="biol." lang="fi">biologia</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="биол." lang="ru">биология</name>
   </item>
   <item>
      <name abbr="bot." lang="en">botany</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="бот." lang="ru">ботаника</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="бран." lang="ru">бранное слово, выражение</name>
   </item>
   <item>
      <name abbr="fut." lang="en">future</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">локтан кад</name>
      <name abbr="буд. вр." lang="ru">будущее время</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="букв." lang="ru">буквально</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="б.ч." lang="ru">большей частью</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вводн. сл." lang="ru">вводное слово</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вет." lang="ru">ветеринария</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="взаимн." lang="ru">взаимный залог</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">вежӧртасын</name>
      <name abbr="в знач." lang="ru">в значении</name>
   </item>
   <item>
      <name abbr="acc." lang="en">accusative case</name>
      <name abbr="akk." lang="fi">akkusatiivi</name>
      <name abbr="xx" lang="kv">керан вежлӧг</name>
      <name abbr="вин. п." lang="ru">винительный падеж</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вм." lang="ru">вместо</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="воен." lang="ru">военный термин</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="возвр." lang="ru">возвратное (залог, местоимение)</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вопр." lang="ru">вопросительное (местоимение, частица)</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вр." lang="ru">время</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="в разн. знач." lang="ru">в разных значениях</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="врем." lang="ru">временный вид</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вспом." lang="ru">вспомогательный (глагол)</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="в ст." lang="ru">в статье</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вступ. п." lang="ru">вступительный падеж</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="выдел." lang="ru">выделительное</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="высок." lang="ru">высокого стиля</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="вычисл." lang="ru">вычислительное</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="геогр." lang="ru">география</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="геод." lang="ru">геодезия</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="геол." lang="ru">геология</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="геом." lang="ru">геометрия</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="гидрол." lang="ru">гидрология</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="гидротех." lang="ru">гидротехнический термин</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="гл." lang="ru">глагол</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="гл. обр." lang="ru">главным образом</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="горн." lang="ru">горняцкий термин, горное дело</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="грам." lang="ru">грамматическое</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="груб." lang="ru">грубое слово, выражение</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="дат. п." lang="ru">дательный падеж</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="деепр." lang="ru">деепричастие</name>
   </item>
   <item>
      <name abbr="xx" lang="en">xxx</name>
      <name abbr="xx" lang="fi">xxx</name>
      <name abbr="xx" lang="kv">xxx</name>
      <name abbr="действ." lang="ru">действительный залог</name>
