=== giellalt/lang-kpv/src/dict.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<!-- definition of simple elements -->
<xs:element name="abbr" type="xs:string"/>
<xs:element name="acron" type="xs:string"/>
<xs:element name="dom" type="xs:string"/>
<xs:element name="isa" type="xs:string"/>
<xs:element name="komi" type="xs:string"/>
<xs:element name="lemma" type="xs:string"/>
<xs:element name="msp" type="xs:string"/>
<xs:element name="sci" type="xs:string"/>
<xs:element name="stem" type="xs:string"/>
<xs:element name="syn" type="xs:string"/>
<xs:element name="syno" type="xs:string"/>
<xs:element name="variant" type="xs:string"/>



<!-- definition of complex elements -->

<xs:element name="article">
  <xs:complexType>
    <xs:choice>

      <xs:complexType>
	<xs:sequence>
	  <xs:complexType maxOccurs="unbounded" minOccurs="0">
	    <xs:sequence>
	      <xs:element ref="der" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="dom" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="dial" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="isa" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="syn" maxOccurs="unbounded" minOccurs="0"/>
	    </xs:sequence>
	  </xs:complexType>
	  <xs:complexType>
	    <xs:sequence>
	      <xs:element ref="eng"/>
	      <xs:element ref="fin"/>
	      <xs:element ref="sci" maxOccurs="1" minOccurs="0"/>
	    </xs:sequence>
	  </xs:complexType>
	  <xs:complexType maxOccurs="unbounded" minOccurs="0">
	    <xs:sequence>
	      <xs:element ref="cf" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="msp" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="pro" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="see" maxOccurs="1" minOccurs="0"/>
	      <xs:element ref="syno" maxOccurs="1" minOccurs="0"/>
	    </xs:sequence>
	  </xs:complexType>
	</xs:sequence>
      </xs:complexType>

      <xs:complexType>
	<xs:sequence>
	  <xs:element ref="eg" maxOccurs="unbounded" minOccurs="1"/>
	</xs:sequence>
      </xs:complexType>

    </xs:choice>
  </xs:complexType>
</xs:element>

<xs:element name="cf" mixed="true">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="choice"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="choice">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="variant" maxOccurs="unbound"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


<xs:element name="der">
  <xs:complexType>
    <xs:choice>
      <xs:complexType>
	<xs:sequence>
	  
	</xs:sequence>
      </xs:complexType>
      <xs:complexType>
	<xs:sequence>
	  <xs:element ref="variant" maxOccurs="unbound"/>
	</xs:sequence>
      </xs:complexType>
    </xs:choice>
  </xs:complexType>
</xs:element>


<xs:element name="eg">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="komi"/>
      <xs:element ref="eng"/>
      <xs:element ref="fin"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="eng" mixed="true">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="choice"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="entryGroup">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="entry" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="entry">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="lemma"/>
      <xs:element ref="stem"/>
      <xs:element ref="contlex"/>
      <xs:element ref="pos"/>
      <xs:element ref="article" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="fin" mixed="true">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="choice"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="pro" mixed="true">
  <xs:complexType>
    <xs:sequence>
      <xs:element ref="choice"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>



<!-- definition of complex elements with mixed='true' -->
<xs:element name="sent">
  <xs:complexType mixed="true">
    <xs:sequence maxOccurs="unbounded">
      <xs:element ref="punct" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element ref="br" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element ref="emp" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>

<xs:element name="contlex">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="ACRON"/>
      <xs:enumeration value="Adj"/>
      <xs:enumeration value="ADV"/>
      <xs:enumeration value="CARD2b"/>
      <xs:enumeration value="CARD2"/>
      <xs:enumeration value="CARD"/>
      <xs:enumeration value="DoubleVerb1"/>
      <xs:enumeration value="End1a"/>
      <xs:enumeration value="End1"/>
      <xs:enumeration value="End2"/>
      <xs:enumeration value="EndA"/>
      <xs:enumeration value="EndConj"/>
      <xs:enumeration value="EndIndef"/>
      <xs:enumeration value="EndInteRJ"/>
      <xs:enumeration value="EndNeg"/>
      <xs:enumeration value="EndPart"/>
      <xs:enumeration value="EndRefl"/>
      <xs:enumeration value="F"/>
      <xs:enumeration value="Noun1"/>
      <xs:enumeration value="NounDET"/>
      <xs:enumeration value="NounLA"/>
      <xs:enumeration value="NounMort"/>
      <xs:enumeration value="NounOBJ"/>
      <xs:enumeration value="NounPi"/>
      <xs:enumeration value="NounPL"/>
      <xs:enumeration value="NounPOSS"/>
      <xs:enumeration value="NounSG"/>
      <xs:enumeration value="NounSUBJ"/>
      <xs:enumeration value="NUM"/>
      <xs:enumeration value="POSTP1a"/>
      <xs:enumeration value="POSTP"/>
      <xs:enumeration value="PRON3"/>
      <xs:enumeration value="PRON4b"/>
      <xs:enumeration value="PRON4"/>
      <xs:enumeration value="PRON"/>
      <xs:enumeration value="PRONdz4i3k"/>
      <xs:enumeration value="PRONPL12"/>
      <xs:enumeration value="PRONSG12"/>
      <xs:enumeration value="VConjCons"/>
      <xs:enumeration value="VConjVow"/>
      <xs:enumeration value="Vdz4i3k"/>
      <xs:enumeration value="Verb1"/>
      <xs:enumeration value="Verb2"/>
      <xs:enumeration value="Verb3"/>
      <xs:enumeration value="VerbPRT"/>
      <xs:enumeration value="Verbve3c4"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>

<xs:element name="pos">
  <xs:simpleType>
    <xs:restriction base="xs:string">
      <xs:enumeration value="ADV"/>
      <xs:enumeration value="ADVROOT"/>
      <xs:enumeration value="A"/>
      <xs:enumeration value="CONJ"/>
      <xs:enumeration value="CONJ-ADVERSATIVE"/>
      <xs:enumeration value="DEM"/>
      <xs:enumeration value="F"/>
      <xs:enumeration value="GER"/>
      <xs:enumeration value="IDIOM"/>
      <xs:enumeration value="INDEF"/>
      <xs:enumeration value="INTERJ"/>
      <xs:enumeration value="INTER"/>
      <xs:enumeration value="NEG"/>
      <xs:enumeration value="NN"/>
      <xs:enumeration value="N"/>
      <xs:enumeration value="NUM"/>
      <xs:enumeration value="ONOM"/>
      <xs:enumeration value="ORD"/>
      <xs:enumeration value="PART"/>
      <xs:enumeration value="PERS"/>
      <xs:enumeration value="POSTP"/>
      <xs:enumeration value="PRON"/>
      <xs:enumeration value="PROP"/>
      <xs:enumeration value="QUANT"/>
      <xs:enumeration value="REFL"/>
      <xs:enumeration value="REL"/>
      <xs:enumeration value="SUPERL"/>
      <xs:enumeration value="VDER"/>
      <xs:enumeration value="V"/>
      <xs:enumeration value="VNEG"/>
      <xs:enumeration value="V-INST"/>
    </xs:restriction>
  </xs:simpleType>
</xs:element>


<!-- Actual dict -->
<xs:element name="dict">
<xs:complexType>
    <xs:sequence>
      <xs:element ref="entryGroup" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:element>


</xs:schema>

=== giellalt/lang-kpv/src/working_files/PROP-RUSSIAN-TOPONYMS_kom-lex.xml
<?xml version="1.0" encoding="UTF-8"?>
<dict xsi:noNamespaceSchemaLocation="../dict.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:hfp="http://www.w3.org/2001/XMLSchema-hasFacetAndProperty"
      xmlns:fn="http://www.w3.org/2005/02/xpath-functions">
   <!-- This contains place names and toponyms that are 100% equivalent to their Russian counterparts. This list will be available for other languages written in the Cyrillic alphabet. -->
   <entry>
      <lemma>Татарстан</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Казань</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Азия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Австралия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Европа</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Гольфстрим</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Мордовия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Абхазия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Болгария</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Ижевск</lemma>
      <stem>Ижевск2</stem>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Карелия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Краснодар</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Москва</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Петербург</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Албания</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Америка</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Англия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Архангельск</lemma>
      <stem>Архангельск2</stem>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Атлантика</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Балтия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Боливия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Бразилия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Чечня</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Чернобыль</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Чили</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Дания</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Эстония</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Египет</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Екатеринбург</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Финляндия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Франция</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Германия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Греция</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Индия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Ингерманландия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Исландия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Италия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Израиль</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Кипр</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Киров</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Китай</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Княжпогост</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Кореа</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Котлас</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Маньчжурия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Микунь</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Молдавия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Норвегия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Новгород</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Печора</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Польша</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Португалия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Прибалтика</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Пруссия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Рим</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Россия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Швеция</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Салехард</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Скандинавия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Сомали</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Сосногорск</lemma>
      <stem>Сосногорск2</stem>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>США</lemma>
      <stem/>
      <contlex>ACRON</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>СНГ</lemma>
      <stem/>
      <contlex>ACRON</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Сибир</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Стокгольм</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Тюмень</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Турция</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Югославия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Удмуртия</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Волга</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Вологда</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
   <entry>
      <lemma>Воркута</lemma>
      <stem/>
      <contlex>Prop-Plc-Rus</contlex>
      <pos>PROP</pos>
   </entry>
</dict>

=== giellalt/lang-kpv/src/working_files/ACRON_kom-lex.xml
<?xml version="1.0" encoding="UTF-8"?>
<dict xsi:noNamespaceSchemaLocation="../dict.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <entry>
      <lemma>АК</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>АО</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>АОЗТ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>АПК</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>АССР</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>АТП</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>АЭК</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ВИЧ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ГАП</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ДВП</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ДРСУ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ДСП</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ЖЭК</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>КР</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ЛПК</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>НГП</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>НКГБ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>НПГ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>НПЗ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>НПСР</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ПМК</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ПФ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>РСКБ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>РСФСР</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>РФ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>РФЖК</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>РЭУ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>САУ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>СП</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>СПИД</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>СССР</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ТОО</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>УВД</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>УНПО</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
   <entry>
      <lemma>ЦБ</lemma>
      <stem/>
      <contlex>Noun1-IS_ACRON</contlex>
      <pos>N</pos>
   </entry>
</dict>
