=== giellalt/lang-kpv/src/dict.dtd
<!ELEMENT dict (entry+) >


<!ELEMENT entry (lemma, stem?, contlex, POS, article?) >
 <!ELEMENT lemma (#PCDATA) >
 <!ELEMENT stem (#PCDATA) >
 <!ELEMENT contlex (#PCDATA) >
 <!ELEMENT POS (#PCDATA) >
 <!ELEMENT article (EG?, ENG?, FIN?, ) >
  <!ELEMENT EG (KOMI, ENG, FIN) >
 <!ELEMENT KOMI (#PCDATA) >
 <!ELEMENT ENG (#PCDATA) >
 <!ELEMENT FIN (#PCDATA) >
 <!ELEMENT DOM (#PCDATA) >
 <!ELEMENT SCI (#PCDATA) >
 <!ELEMENT SYNO (#PCDATA) >
 <!ELEMENT DER (#PCDATA) >
 <!ELEMENT SEE (#PCDATA) >
 <!ELEMENT ABBR (#PCDATA) >
 <!ELEMENT ACRON (#PCDATA) >
 <!ELEMENT ANT (#PCDATA) >
 <!ELEMENT BIB (#PCDATA) >
 <!ELEMENT CF (#PCDATA) >
 <!ELEMENT COMM (#PCDATA) >
 <!ELEMENT CONN (#PCDATA) >
 <!ELEMENT DIAL (#PCDATA) >
 <!ELEMENT METEOR (#PCDATA) >
 <!ELEMENT MSP (#PCDATA) >
 <!ELEMENT PRO (#PCDATA) >
 <!ELEMENT PROP (#PCDATA) >
 <!ELEMENT SPELL (#PCDATA) >
 <!ELEMENT SYN (#PCDATA) >
 <!ELEMENT V-al (#PCDATA) >


<!-- old dtd, for reference: 

   <!ELEMENT trans (#PCDATA)>
   <!ELEMENT grammtrans (consgradation?, stem?, attr?, government?)>
    <!ELEMENT consgradation (#PCDATA)>
    <!ELEMENT stem (#PCDATA)>
    <!ELEMENT attr (#PCDATA)>
    <!ELEMENT government (#PCDATA)>
  <!ELEMENT comment (#PCDATA)>
  <!ELEMENT exgroup (ex, extrans)>
   <!ELEMENT ex (#PCDATA)>
   <!ELEMENT extrans (#PCDATA)>
-->

=== giellalt/lang-kpv/inc/MaleNicknames4kom-lex.xml
<?xml version="1.0" encoding='utf-8'?><!DOCTYPE dict SYSTEM "dict.dtd" >
<dict>

<entry>
  <lemma>Авгусёв_род</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Авко_Миш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Агни_Миш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Адам_Кöсьта</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Аким_Педь</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Акö_Мишö_Петьö_Коля</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Ало_Вась</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Альö_Илля</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Амиль_Егор</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Амос_Педöр</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Андрик_Мишö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Анань_Гень</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Андил_Васьö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Андигел_Васьö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Антип_Мишка</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Анча_Микол</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Анэ_Лень</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Арда_Вань</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Ардаш_Öгаш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Аркирей_пи</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Арсе_Егор</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Арсей_Паш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Арсень_Глеб</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Арсень_Миш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Арсень_Мишö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Арт_Öнись_Епим</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Атань_Павел</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Баба_Вань</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Багаёв_Öльöксан</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Багай_Öндрей</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бае_Семö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>База_Вань</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Байдöг_Микайлö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бака_Миш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Баку_Миш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Балки_Микöл</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бальзан_Егор</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Баля_Кок_Егор</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Баля_Митрей</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Банкир_Лень</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Барин_Мишка</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Барко_Коля</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Батур_Паш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Беддя_Еремей</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бекар_Васька</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Белько_Офонь</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Белэй_Володя</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бертан_Миколай</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бобö_Иван</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бодёр_пиян</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Болки_Микöл</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Борис_Кольö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бобыль_Вель</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бöрдысь_Степан</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бöрö_Митрей</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бральскöй_Микита</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Буби_Öльöксей</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бузук_Сень</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Буржуй_Мишка</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бурлак_Вась</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Буткан_Степан</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Бызö_Николай</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Ваган_Осип</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Вадор_Миш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Валь_Зöсим</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Вальö_Васьö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Валя_Öльöш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Вань_Вань</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Вань_Сандрик_Петрö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Ванька_Паш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Варган_Вась</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Варгыль_Кöсьта</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Варка_Павел</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Варук_Колю_Онтон</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Варыш_Микул</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Василь_Педьö</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Васти_Öльöш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Вась_Öльöш_Педь</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Васька_Вась</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Васька_Йöрш</lemma>
  <stem/>
  <contlex>Noun1</contlex>
  <POS>MaleNickName</POS>
  <article/>
</entry>

<entry>
  <lemma>Васька_Марка</lemma>
  <stem/>
